<?php

namespace LGELmashBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasserRepository extends EntityRepository
{
    public function findTopNCategorie($n, $categorie_id)
    {
        $em = $this->getEntityManager();

        $queryBuilder = $em->createQueryBuilder()
            ->select('j.pseudo, ca.libelle, cl.elo, ca.id')
            ->from('LGELmashBundle:Classer', 'cl')
            ->from('LGELmashBundle:Joueur', 'j')
            ->from('LGELmashBundle:Categorie', 'ca')
            ->where("cl.categorie = ca.id")
            ->andWhere("cl.joueur = j.id")
            ->andWhere("ca.id = $categorie_id")
            ->orderBy('cl.elo', 'DESC')
            ->setMaxResults($n);

        return $queryBuilder->getQuery()->getResult();
    }
}
