<?php

namespace LGELmashBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Twig\Tests\NodeVisitor\TranslationDefaultDomainNodeVisitorTest;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends EntityRepository
{
    public function findRandomEligibleJoueurs($n)
    {
        $result = array();

        $joueurs = $this->findAll();
        shuffle($joueurs);

        $selected = 0;
        for($i = 0; $selected < $n; $i++){
            if($joueurs[$i]->getCan_be_voted() == true) {
                $selected++;
                $result[] = $joueurs[$i];
            }
        }

        return $result;
    }
}
